---
# Unique prefix: CRV
# Create a random Ansible password vault based on the settings in vault-settings.yml
# Test the vault created using test-vault.yml
# $ ansible-playbook books/create-vault.yml
- name: Create a random vault
  hosts: localhost
  vars_files: ../vars/vault-settings.yml
  tasks:

  - name: CRV-7636
    set_fact:
      pw: "{{ lookup('password', '/dev/null length=32') }}"

  - name: CRV-9844
    become: no
    local_action:
      module: copy
      content: '{{ pw }}'
      dest: ../vaults/secret
      mode: '0400'

  - name: CRV-7578
    loop: '{{ passwords }}'
    set_fact:
      gen_pw: '{{ gen_pw | default({}) | combine({ "password_%s" % item.name: lookup("password", "/dev/null %s" % item.generator) }) }}'

  - name: CRV-2649
    set_fact:
      random_filename: 'tempfile-{{ lookup("password", "/dev/null length=8 chars=ascii_lowercase,digits") }}'

  - name: CRV-5643
    become: no
    with_dict: '{{ gen_pw }}'
    no_log: True
    local_action:
      module: lineinfile
      create: yes
      line: '{{ item.key }}: {{ item.value }}'
      dest: /dev/shm/{{ random_filename }}

  - name: CRV-9223
    become: no
    local_action:
      module: command
      cmd: ansible-vault encrypt --vault-password-file=../vaults/secret /dev/shm/{{ random_filename }} --output ../vaults/{{ vault_name }}

...
